// filepath: f:\hackthon\Ballerina\Healthcare\Healthcare\Ballerina.toml
[package]
org = "acer"
name = "Healthcare"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[dependencies]
ballerinax/mysql = "1.13.1"

[[platform.java11.dependency]]
path = "./libs/mysql-connector-j-9.0.0.jar"
artifactId = "mysql-connector-java"
version = "9.0.0"